# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_sceua_wrappers", use_symbols = TRUE, package_name = "sceua")

#' @usage NULL
#' @useDynLib sceua, .registration = TRUE
NULL

sceua_minimize <- function(fn, lower, upper, max_evaluations, kstop, pcento, seed, complexes, points_per_complex, simplex_size, evolution_steps, min_complexes, include_initial, initial_point, parameter_epsilon) .Call(wrap__sceua_minimize, fn, lower, upper, max_evaluations, kstop, pcento, seed, complexes, points_per_complex, simplex_size, evolution_steps, min_complexes, include_initial, initial_point, parameter_epsilon)


# nolint end
